# Use an official Python runtime as a parent image
FROM python:3.12-slim-bookworm

ENV UV_VERSION=0.7.2
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_CONCURRENT_INSTALLS=20

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    curl \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install UV using pip and clear cache
RUN pip install --no-cache-dir "uv==$UV_VERSION"

# Set the working directory
WORKDIR /app

# Copy the pyproject.toml and uv.lock files from the root directory
COPY ./pyproject.toml ./uv.lock ./

# Install the dependencies and clear cache
RUN uv sync --active --locked \
    && rm -rf ~/.cache/uv/cache/ ~/.cache/uv/artifacts/

# Copy the data_cdc and core directories
COPY ./src/data_cdc ./data_cdc
COPY ./src/core ./core

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/app

# Command to run the script
CMD ["uv", "run", "python", "-m", "data_cdc.cdc"]